apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-hpa
  namespace: homelab
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
  minReplicas: 2    # Nunca bajar de 2 (alta disponibilidad mínima)
  maxReplicas: 6    # Nunca superar 6 (protección del nodo)
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50    # Escala cuando la CPU media supere el 50% del request
