apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: freescout-ingress
  namespace: homelab
spec:
  ingressClassName: traefik
  rules:
    - host: helpdesk.homelab.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: freescout
                port:
                  number: 80
