apiVersion: v1
kind: Secret
metadata:
  name: freescout-db-secret
  namespace: homelab
type: Opaque
data:
  db-host: bWFyaWFkYg==         # mariadb
  db-name: ZnJlZXNjb3V0         # freescout
  db-user: ZnJlZXNjb3V0dXNlcg== # freescoutuser
  db-pass: ZnJlZXNjb3V0cGFzcw== # freescoutpass
