apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: homelab
type: Opaque
data:
  # Valores en base64. Decodificar: echo "cm9vd..." | base64 -d
  root-password: cm9vdHBhc3N3b3Jk   # rootpassword
  db-user: aG9tZWxhYnVzZXI=         # homelabuser
  db-password: aG9tZWxhYnBhc3M=     # homelabpass
  db-name: aG9tZWxhYmRi             # homelabdb
