apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: homelab
spec:
  clusterIP: None          # Esto lo hace "headless": no crea IP virtual, devuelve IPs de pods directamente
  selector:
    app: mariadb
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
